import {
  Archive,
  BarChart3,
  Bell,
  CalendarCheck2,
  CheckCircle2,
  ChevronRight,
  Clock3,
  DollarSign,
  Download,
  Filter,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  Package,
  Plus,
  Search,
  Send,
  Star,
  X,
} from "lucide-react";

export const dashboardIcons = {
  analytics: BarChart3,
  archive: Archive,
  bell: Bell,
  bookings: CalendarCheck2,
  check: CheckCircle2,
  chevronRight: ChevronRight,
  clock: Clock3,
  dollar: DollarSign,
  download: Download,
  filter: Filter,
  mapPin: MapPin,
  messages: MessageSquare,
  overview: LayoutDashboard,
  packages: Package,
  plus: Plus,
  search: Search,
  send: Send,
  star: Star,
  close: X,
};
